config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  devise_for :users, :controllers =>{
    registrations: 'users/registrations'  # AM: +1 overriding Devise's registrations controller
  }

  resources :users do
    resources :assessments
    resources :memories
    resources :goals
  end
  get'/crisis', to: 'welcome#crisis', as: :crisis

  root to: 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assessment.rb
class Assessment < ApplicationRecord
  # AM: Encourage you to look into Rails Validations. Great way to place Rails-level constraints on your data. Easy to learn and will look good to potential employers that use Rails.
  belongs_to :user
end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :user
end

app/models/memory.rb
class Memory < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :assessments, dependent: :destroy
  has_many :memories, dependent: :destroy
  has_many :goals, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/assessments_controller.rb
class AssessmentsController < ApplicationController

  def index
    @assessments = Assessment.all.order(updated_at: :desc)
  end

  def show
    @assessment = Assessment.find(params[:id])
  end

  def new
    @user = current_user
    @assessment = Assessment.new
  end

  def create
    @assessment= Assessment.new(assessment_params)
    @assessment.user = current_user
    @assessment.save

    if @assessment.score == 1
      redirect_to crisis_path
    # AM: The next three options all look identical (except for the score). You could use `<` and `>` in a single conditional statement to account for them all.
    elsif @assessment.score == 2
      redirect_to user_memories_path
      flash[:notice] = "It sounds like you're feeling down right now. Here are some positive memories to remind you that it can't rain all the time."
    elsif @assessment.score == 3
      redirect_to user_memories_path
      flash[:notice] = "It sounds like you're feeling down right now. Here are some positive memories to remind you that it can't rain all the time."
    elsif @assessment.score == 4
      redirect_to user_memories_path
      flash[:notice] = "It sounds like you're feeling down right now. Here are some positive memories to remind you that it can't rain all the time."
    # AM: Ditto my earlier comment with these next three condtions. You couls also flash the correct score by replacing the hard-coded number with `@assessment.score`
    elsif @assessment.score == 5
      redirect_to user_goals_path
      flash[:notice] = "Ok. What would it take to get you to a 6?"
    elsif @assessment.score == 6
      redirect_to user_goals_path
      flash[:notice] = "Ok. What would it take to get you to a 7?"
    elsif @assessment.score == 7
      redirect_to user_goals_path
      flash[:notice] = "Ok. What would it take to get you to an 8?"
    # AM: Ditto my first conditional-related comment for the next three options
    elsif @assessment.score == 8
      redirect_to new_user_memory_path
      flash[:notice] = "That's great. Why don't you record one thing that made you smile today."
    elsif @assessment.score == 9
      redirect_to new_user_memory_path
      flash[:notice] = "That's great. Why don't you record one thing that made you smile today."
    elsif @assessment.score == 10
      redirect_to new_user_memory_path
      flash[:notice] = "That's great. Why don't you record one thing that made you smile today."
    end
  end

  private
  def assessment_params
    params.require(:assessment).permit(:score)
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController

  def index
    @goals = Goal.all
  end

  def show
    @goal = Goal.find(params[:id])
  end

  def edit
    # AM: Can't you just reference `current_user` in your view instead of saving it to a `@user` variable?
    @user = current_user
    @goal = Goal.find(params[:id])
  end

  def new
    @user = current_user
    @goal = Goal.new
  end

  def create
    @goal = Goal.new(goal_params)
    @goal.user = current_user
    @goal.save
    redirect_to user_goals_url
  end

  def update
    @goal = Goal.find(params[:id])
    @goal.update(goal_params)
    redirect_to user_goals_url(current_user)
  end

  def destroy
    @goal = Goal.find(params[:id])
    @goal.destroy
    redirect_to user_goals_path
  end

  private
  def goal_params
    params.require(:goal).permit(:goal_string, :deadline)
  end
end

app/controllers/memories_controller.rb
class MemoriesController < ApplicationController

  def index
    @memories = Memory.all
  end

  def show
    @memory = Memory.find(params[:id])
  end

  def new
    @user = current_user
    @memory = Memory.new
  end

  def create
    @memory = Memory.new(memory_params)
    @memory.user = current_user
    @memory.save
    redirect_to user_memories_url
  end

  private
  def memory_params
    params.require(:memory).permit(:narrative)
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
before_action :configure_sign_up_params, only: [:create]
before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @user = current_user
    if current_user.assessments.order(:created_at).last
      @last_assessment = current_user.assessments.order(:created_at).last.created_at.time.to_date
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assessments_helper.rb
module AssessmentsHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/memories_helper.rb
module MemoriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/assessments/index.html.erb
<h2>Assessments</h2>
<table>
  <tr>
    <th>Date</th>
    <th>Score</th>
  </tr>
  <% current_user.assessments.each do |assessment| %>
    <tr>
      <td><%= assessment.created_at.time.to_date %> </td>
      <td><%= assessment.score %> </td>
    </tr>
  <% end %>
</table>

app/views/assessments/new.html.erb
<h2>New Assessment</h2>
<%= form_for([current_user, @user.assessments.build]) do |f| %>
  <p>
    <%= f.label :score %><br>

    <%= f.select :score, (1..10) %><br>  <!-- AM: Nice -->
  </p>
  <p>
    <%= f.submit %>
  </p>
  <% end %>

app/views/goals/edit.html.erb
<h3>Edit goal</h3>
<!-- AM: You shouldn't need to explicitly say `method: :put` if `@goal` contains an existing goal. -->
<%= form_for [@user, @goal], method: :put do |f| %>
  <p>
    <%= f.label :goal_string %><br>
    <div class="textbox">
      <%= f.text_area :goal_string %><br>
    </div>
  </p>
  <p>
    <%= f.label :deadline %><br>
    <%= f.text_field :deadline %><br>
  </p>
  <p>
    <%= f.submit %>
  </p>
  <% end %>

app/views/goals/index.html.erb
<h3>Goals</h3>
<div class="row">
<div class="well column col-md-6">
  <p>Setting goals is an important part of building sustainable wellness. Focus on changes you can make, and be as specific as possible. "I want to lose weight" is a noble sentiment, but as a goal, it doesn't do much to guide changes in behavior. "I will eat better and exercise to lose weight" is better. It says what you will do, and ties your behavioral changes to your goal. "I will eat less sugary snacks" or "I will walk/run at least fifteen minutes three times a week" are great. They define specific, measurable changes that are entirely within your control. </p>
  <!-- <p> </p> -->
</div>
<div class="well column col-md-6">
<table>
  <tr>
    <th>Date</th>
    <th>Goal</th>
    <th>Complete By</th>
  </tr>
  <% current_user.goals.each do |goal| %>
    <tr>
      <td><%= goal.created_at.time.to_date %> </td>
      <td><%= goal.goal_string %> </td>
      <td><%= goal.deadline %> </td>
      <td><%= link_to 'Edit', edit_user_goal_path(current_user, goal) %> </td>
      <td><%= link_to 'Completed/Remove', user_goal_path(current_user, goal), method: :delete, data: {confirm: 'Do you want to remove this goal?'} %> </td>
    </tr>
  <% end %>
</table>
<%= link_to 'Create New Goal', new_user_goal_path(current_user) %><br>
</div>
</div>
<button><%= link_to 'Back', root_url %></button>

app/views/goals/new.html.erb
<h3>What can you do to take your score to the next level?</h3>
<%= form_for([current_user, @user.goals.build]) do |f| %>
  <p>
    <%= f.label :goal_string %><br>
    <div class="textbox">
      <%= f.text_area :goal_string %><br>
    </div>
  </p>
  <p>
    <%= f.label :deadline %><br>
    <%= f.text_field :deadline %><br>
  </p>
  <p>
    <%= f.submit %>
  </p>
  <% end %>

app/views/goals/show.html.erb
<h3>Goal progress</h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wellnyss</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Fredoka+One|Indie+Flower|Knewave|Raleway" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
    <header class="well banner">
      <nav>
        <% if !current_user  %>

          <%= link_to 'Sign Up', new_user_registration_path %> |
          <%= link_to 'Sign In', new_user_session_path %>

        <%else %>
          <%= current_user.first_name %> |
          <%= link_to 'Edit User Settings', edit_user_registration_path %> |
          <%= link_to 'Help', crisis_path %> |
          <%= link_to 'Log Out', destroy_user_session_path, method: :delete %>

        <% end %>
      </nav>
      <h1><span class='brand'><%= link_to "Wellnyss", root_url %></span></h1>
      <h4 class="tagline">A user-centered mental health and wellness app</h4>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </header>
    <%= yield %>
  </body>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</html>

app/views/memories/index.html.erb
<h2> Remember when... </h2>
<div class="row">
  <div class="well column col-md-6">
<table>
  <!-- <tr>
    <th>Date</th>
    <th>Narrative</th>
  </tr> -->
  <% current_user.memories.each do |memory| %>
    <tr>
      <td><%= memory.created_at.time.to_date %> </td>
      <td><%= memory.narrative %> </td>
    </tr>
  <% end %>
</table>
<%= link_to 'Add New Memory', new_user_memory_path(current_user) %><br>
</div>
<div class="well column col-md-6">
  <p>If you're stuck, try answering these questions:</p>
  <article>
    <p class="strong">Are you hydrated?</p>
    <p> If not, have a glass of water.</p>
  </article>
  <article>
    <p class="strong">Have you eaten in the past three hours?</p>
    <p>If not, get some food — something with protein, not just simple carbs.  Perhaps some nuts or hummus?</p>
  </article>
  <article>
    <p class="strong">Have you showered in the past day?</p>
    <p>If not, take a shower right now.</p>
  </article>
  <article>
    <p class="strong">If daytime: are you dressed? </p>
    <p> If not, put on clean clothes that aren’t pajamas.  Give yourself permission to wear something special, whether it’s a funny t-shirt or a pretty dress.</p>
  </article>
  <article>
    <p class="strong">If nighttime: are you sleepy and fatigued but resisting going to sleep?</p>
    <p>Put on pajamas, make yourself cozy in bed with a teddy bear and the sound of falling rain, and close your eyes for fifteen minutes — no electronic screens allowed.  If you’re still awake after that, you can get up again; no pressure.</p>
  </article>
  <article>
    <p class="strong">Have you stretched your legs in the past day? </p>
    <p>If not, do so right now.  If you don’t have the spoons for a run or trip to the gym, just walk around the block, then keep walking as long as you please.  If the weather’s crap, drive to a big box store (e.g. Target) and go on a brisk walk through the aisles you normally skip.</p>
  </article>
  <article>
    <p class="strong">Have you said something nice to someone in the past day? </p>
    <p>Do so, whether online or in person.  Make it genuine; wait until you see something really wonderful about someone, and tell them about it.</p>
  </article>
  <article>
    <p class="strong">Have you moved your body to music in the past day?</p>
    <p> If not, do so — jog for the length of an EDM song at your favorite BPM, or just dance around the room for the length of an upbeat song.</p>
  </article>
  <article>
    <p class="strong">Have you cuddled a living being in the past two days?</p>
    <p> If not, do so.  Don’t be afraid to ask for hugs from friends or friends’ pets.  Most of them will enjoy the cuddles too; you’re not imposing on them.</p>
  </article>
  <article>
    <p class="strong">Do you feel ineffective?</p>
    <p>Pause right now and get something small completed, whether it’s responding to an e-mail, loading up the dishwasher, or packing your gym bag for your next trip.  Good job!</p>
  </article>
  <article>
    <p class="strong">Do you feel unattractive? </p>
    <p> Take a selfie.  Your friends will remind you how great you look, and you’ll fight society’s restrictions on what beauty can look like.</p>
  </article>
  <article>
    <p class="strong">Do you feel paralyzed by indecision?</p>
    <p>Give yourself ten minutes to sit back and figure out a game plan for the day.  If a particular decision or problem is still being a roadblock, simply set it aside for now, and pick something else that seems doable.  Right now, the important part is to break through that stasis, even if it means doing something trivial.</p>
  </article>
  <article>
    <p class="strong">Have you been over-exerting yourself lately — physically, emotionally, socially, or intellectually?</p>
    <p>That can take a toll that lingers for days. Give yourself a break in that area, whether it’s physical rest, taking time alone, or relaxing with some silly entertainment.</p>
  </article>
  <a href="http://eponis.tumblr.com/post/113798088670/everything-is-awful-and-im-not-okay-questions-to">Source</a>
</div>
</div>
<button><%= link_to 'Back', root_url %></button>

app/views/memories/new.html.erb
<h2>Record one thing that made you smile today</h2>

<%= form_for([current_user, @user.memories.build]) do |f| %>
  <p>
    <%= f.label :narrative %><br>
    <div class="textbox">
      <%= f.text_area :narrative %><br>
    </div>
  </p>
  <p>
    <%= f.submit %>
  </p>
  <% end %>

app/views/welcome/crisis.html.erb
<h1>You're not alone</h1>
<div class="well column">
  <p>Here are some resources to talk to someone about what's going on.</p>
  <p><a href='http://chat.suicidepreventionlifeline.org/GetHelp/LifelineChat.aspx'>Suicide Prevention Chat Line</a></p>
  <p> Call 1-800-273-8255 24 hours a day, 7 days a week.</p>
  <a href="http://www.nami.org/Find-Support/NAMI-HelpLine#crisis">NAMI's crisis resources</a>
</div>
<h2>Additional Resources</h2>
<div class="well column">
  <a href="http://www.nami.org/#">NAMI-National Alliance on Mental Illness</a><br>
  <br>
  <a href="https://www.nimh.nih.gov/health/find-help/index.shtml">NIMH-National Institutes on Mental Health</a><br>
  <br>
  <a href="https://www.mentalhealth.gov/index.html">Health and Human Services</a>

</div>
<button><%= link_to 'Back', root_url %></button>

app/views/welcome/index.html.erb
<% if @last_assessment == Date.current %>
<!-- <h2>Welcome!</h2> -->
<div class="row">
<div class='well column col-md-4'>
  <h3><%= link_to 'Your good memories', user_memories_path(@user) %><%= link_to '(+)', new_user_memory_path(@user) %></h3>

  <table>
    <tr>
      <th>Date</th>
      <th>Narrative</th>
    </tr>
    <% current_user.memories.each do |memory| %>
    <tr>
      <td><%= memory.created_at.time.to_date %> </td>
      <td><%= memory.narrative %> </td>
    </tr>
    <% end %>
  </table>

</div>
<div class='well column col-md-4 flexcont'>
  <h3>Your self-assessment history</h3>
  <table>
    <tr>
      <th>Date</th>
      <th>Score</th>
    </tr>
    <% current_user.assessments.order(updated_at: :desc).each do |assessment| %>
    <tr>
      <td><%= assessment.created_at.time.to_date %> </td>
      <td><%= assessment.score %> </td>
    </tr>
    <% end %>
  </table>

  <!-- <%= link_to 'New assessment', new_user_assessment_path(@user) %> -->
</div>
<div class="well column col-md-4">
  <h3><%= link_to'Your goals', user_goals_path(@user)%><%= link_to '(+)', new_user_goal_path(@user) %></h3>
  <table>
    <tr>
      <th>Date</th>
      <th>Goal</th>
      <th>Complete by</th>
    </tr>
    <% current_user.goals.each do |goal| %>
    <tr>
      <td><%= goal.created_at.time.to_date %> </td>
      <td><%= goal.goal_string %> </td>
      <td><%= goal.deadline %> </td>
      <!-- <td><%= link_to 'Edit', edit_user_goal_path(current_user, goal) %> </td> -->

    </tr>
    <% end %>
  </table>

</div>
</div>
<% else %>

<%= form_for([current_user, @user.assessments.build]) do |f| %>
<p>
  <%= f.label :score %><br>

  <%= f.select :score, (1..10) %><br>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>
<% end %>